name: Create key

on:
  workflow_dispatch:
    inputs:
      host:
        description: 'Meilisearch host'
        required: true
        type: string
      apiKey:
        description: 'Meilisearch api key (w/ enough rights to create a key)'
        required: true
        type: string
      keyUid:
        description: 'Uid of the key (uuid4 format mandatory)'
        required: true
        type: string
      keyDescription:
        description: 'Description of the key'
        default: 'Deterministic key'
        required: true
        type: string
      keyName:
        description: 'Name of the key'
        default: 'deterministic_key'
        required: true
        type: string
      keyActions:
        description: 'Actions the key is allowed to perform (comma separated list)'
        default: 'search'
        required: true
        type: string
      keyIndexes:
        description: 'Indexes on which the key is allowed to perform (comma separated list)'
        default: '*'
        required: true
        type: string

jobs:
  create-deterministic-key:
    runs-on: ubuntu-latest
    name: Create deterministic key
    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
      - name: Install dependencies
        run: yarn --dev
      - name: Create key
        run: yarn create-key
        env:
          MEILI_HTTP_ADDR: ${{ inputs.host }}
          MEILI_API_KEY: ${{ inputs.apiKey }}
          KEY_UUID: ${{ inputs.keyUid }}
          KEY_DESCRIPTION: ${{ inputs.keyDescription }}
          KEY_NAME: ${{ inputs.keyName }}
          KEY_ACTIONS: ${{ inputs.keyActions }}
          KEY_INDEXES: ${{ inputs.keyIndexes }}
